Recipe的一些功能(上傳，搜尋，查看，刪除)
TOPIC114/backend pull request #29
Opened 2024-04-10 12:45 UTC by dddd123fff

upload，上傳功能，author記錄尚未實現
content，查看功能，使用者search紀錄需要修正

2024-04-11 13:54 UTC, bloodnighttw commented
好了告訴我一聲

2024-04-11 13:56 UTC, dddd123fff commented
OK了，看看有沒有什麼需要修改或增加的。

2024-04-11 14:13 UTC, bloodnighttw requested changes

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def create_recipe(info: RecipeUpload, db: AsyncDBSession, user: User = Depends(token_verify)):
response 可以加上他的型態
fastapi的response會顯示他會回傳的結構
這樣會好一點

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def create_recipe(info: RecipeUpload, db: AsyncDBSession, user: User = Depends(token_verify)):
這邊可以指定他的回傳型態為src/response/utils.py的SuccessResponse
我有寫好.

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def create_recipe(info: RecipeUpload, db: AsyncDBSession, user: User = Depends(token_verify)):
具體可以參考我的程式

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def search_recipe(info: RecipeSearch, db: AsyncDBSession):
這邊建議也寫一下你response的格式 應該為 list[RecipeResponse]
其中的RecipeResponse為你要寫pydantic

2024-04-11 14:13 UTC, bloodnighttw commented on src/request/recipe.py
LGTM

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +             .where(search.c.uid == user.id, search.c.rid == rid))
不知道這邊是and邏輯還是or邏輯
可以做註解一下
或者改用and_ 或者or_

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def delete_recipe(rid: int, db: AsyncDBSession, user: User = Depends(token_verify)):
問題同上
可以標示一下回傳的型態結構

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def read_recipe(rid: int, db: AsyncDBSession, user: User = Depends(token_verify)):
問題同上
可以標示一下回傳的型態結構

2024-04-11 14:13 UTC, bloodnighttw commented on src/recipe.py
> +async def create_recipe(info: RecipeUpload, db: AsyncDBSession, user: User = Depends(token_verify)):
喔這類的東西叫做pydantic

2024-04-14 14:05 UTC, bloodnighttw approved these changes
LGTM

2024-04-14 14:06 UTC, merged